version: "3"
services:

  postgres:
    container_name: postgres
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env

  rabbitmq:
    container_name: rabbitmq_bot
    image: rabbitmq:3.11-management
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/
    env_file:
      - .env

  vk_api:
    container_name: vk_api
    build:
      context: .
      dockerfile: dockerfile_vk_api
    env_file:
      - .env
    ports:
      - ${VK_API_PORT}:${VK_API_PORT}
    depends_on:
      - rabbitmq
      - postgres

  game_service:
    container_name: game_service
    build:
      context: .
      dockerfile: dockerfile_game_service
    env_file:
      - .env
    command: bash -c "
      alembic upgrade head
      && python main.py
      "
    ports:
      - ${GAME_SERVICE_PORT}:${GAME_SERVICE_PORT}
    depends_on:
      - postgres

  bot:
    container_name: bot
    build:
      context: .
      dockerfile: dockerfile_bot
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - postgres


volumes:
  postgres_volume:
  rabbitmq_volume: