"""First migration

Revision ID: c2cfc3a1eaed
Revises: 
Create Date: 2023-03-05 19:30:07.078920

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c2cfc3a1eaed"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "game_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("captain_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="game",
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("correct_answer", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("title"),
        schema="game",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("vk_user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vk_user_id"),
        schema="game",
    )
    op.create_table(
        "rounds",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("answer", sa.String(), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("respondent_id", sa.Integer(), nullable=False),
        sa.Column("game_session_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game.game_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["game.questions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["respondent_id"],
            ["game.users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="game",
    )
    op.create_table(
        "user_game_session",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("game_session_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["game_session_id"],
            ["game.game_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["game.users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "game_session_id"),
        schema="game",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_game_session", schema="game")
    op.drop_table("rounds", schema="game")
    op.drop_table("users", schema="game")
    op.drop_table("questions", schema="game")
    op.drop_table("game_sessions", schema="game")
    # ### end Alembic commands ###
