"""First migration

Revision ID: d754e2db142e
Revises: 
Create Date: 2023-03-01 11:08:58.042981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd754e2db142e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captain_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='game'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vk_user_id'),
    schema='game'
    )
    op.create_table('user_game_session',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('game_session', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_session'], ['game.game_sessions.id'], ),
    sa.ForeignKeyConstraint(['user'], ['game.users.id'], ),
    sa.PrimaryKeyConstraint('user', 'game_session'),
    schema='game'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_game_session', schema='game')
    op.drop_table('users', schema='game')
    op.drop_table('rounds', schema='game')
    op.drop_table('game_sessions', schema='game')
    # ### end Alembic commands ###
